name: Ubuntu 20.04

on: 
  workflow_dispatch:
    inputs:
      chrome_access_code:
        description: https://remotedesktop.google.com/headless
        required: true
      pin:
        description: Enter your 6 numbers pin
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          sudo bash ./setting.sh
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz
          unzip ngrok-stable-linux-amd64.tgz
          ./ngrok authtoken 1o79XtSYTbApvdYruCJwpX5kyVJ_4fQ28refmFoEc36iQvgPc
          ./ngrok tcp 5900
      - name: Ubuntu ready to go 
        run: sleep 1d
