name: Ubuntu 20.04

on: 

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          sudo bash ./setting.sh
          DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AX4XfWjXpXE_FPdMpnkMVQ4GP5boXNOtY-ds0CXX6c36O0k0L_iyFikuoixbvWysKjLYsw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname) -pin="123456"
      - name: Ubuntu ready to go 
        run: sleep 1d
