name: Ubuntu 20.04

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          sudo ls /lib/modules/5.11.0-1027-azure
      - name: shell
        run: |
           uname -r
